[package]
name = "quadtrees"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
grid = "0.11"
rand = "0.8"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "search"
harness = false

[workspace]
members = [
    "example",
]